# Vector Spaces {#sec-vector_spaces}

## Real Vector Spaces {#sec-real_vector_spaces}

::: {#def-vectorspace}
**[Real vector space]{style="color: red;"}**

A real vector space is a set $\mc{V}$ over the real numbers $\b{R}$ on which the two operations of $\cdot + \cdot : \mc{V}\times \mc{V} \to \mc{V}$ (addition) and $\cdot * \cdot: \mc{V}\times \b{R}\to \mc{V}$ (scalar multiplication) are defined and satisfies the following properties:
:::

1.  $\bs{u}+\bs{v}=\bs{v}+\bs{u}$ for all $\bs{u},\bs{v} \in \mc{V}$
2.  $\bs{u}+(\bs{v}+\bs{z})= (\bs{u}+\bs{v})+\bs{z}$ for all $\bs{u}, \bs{v}, \bs{z} \in \mc{V}$
3.  $(ab)\bs{v} = a(b\bs{v})$ for all $v \in \mc{V}$ and all $a,b \in \b{R}$
4.  There exists a zero element $\bs{0}_{\mc{V}}$ or simply $\bs{0}$ when there is no risk of confusion, such that $\bs{0} + \bs{v} = \bs{v}$ for all $\bs{v} \in \mc{V}$
5.  For every $\bs{v} \in \mc{V}$, there exists $\bs{v}' \in \mc{V}$ such that $\bs{v} + \bs{v}' = \bs{0}$
6.  $1\bs{v} = \bs{v}$ for all $\bs{v} \in \mc{V}$
7.  $a(\bs{u}+\bs{v}) = a\bs{u} + a\bs{v}$ for all $a,b \in \b{R}$ and all $\bs{u},\bs{v} \in \mc{V}$
8.  $(a+b)\bs{v} = a\bs{v} + b\bs{v}$ for all $a,b \in \b{R}$ and all $\bs{u},\bs{v} \in \mc{V}$

We can show identities such as $-1 * \bs{v}=\bs{v}'$ and $0 * \bs{v}=\bs{0}$ from the above axioms.

$$
\begin{align}
\pr{1+(-1)}\bs{v}&=1*\bs{v}+(-1)*\bs{v}\\
\pr{0}\bs{v}&=1*\bs{v}+(-1)*\bs{v}\\
\bs{0}&=1*\bs{v}+(-1)*\bs{v}\\
\bs{0}&=\bs{v}+(-1)*\bs{v}\\
(-1) * \bs{v}&=\bs{v}'
\end{align}
$$

$$
\begin{align}
\pr{1+0} * \bs{v}&=1 * \bs{v}+(0) * \bs{v}\\
\pr{1} * \bs{v}&=1 * \bs{v}+(0) * \bs{v}\\
\bs{v}&=\bs{v}+(0) * \bs{v}\\
\bs{0}&=(0)*\bs{v}\\
\end{align}
$$

When there is no confusion we will skip explicitly writing $*$, so expressions such as $a * \pr{b \bs{v}}=\pr{ab}  *  \bs{v}$ will appear as $a\pr{b \bs{v}}=\pr{ab}  \bs{v}$

<!-- Examples of real vector spaces include the set of real numbers $\b{R}$ itself and the set of polynomials of order $k$. -->
Examples:

1. $\b{R}^{1} = \b{R}$
2. $\b{R}^{2} = \cpr{\pr{a, b} : a, b \in \b{R}}$
3. $\b{P}^{k}= \cpr{p : \b{R} \ra \b{R} ~\vert~ p(x) = a_{0}+a_{1}x+\dots+a_{k}x^{k}}$

::: {#def-subspace}
**[Subspace]{style="color: red;"}**

A subset $\mc{U}$ of $\mc{V}$ is a *subspace* of $\mc{V}$ if it is also a vector space using the same addition and scalar operation as on $\mc{V}$. 
Namely, $\mc{U}$ is a subspace only if it satisfies, $\bs{0} \in \mc{U}$, $\bs{u} + \bs{v} \in \mc{U}$ for all $\bs{u} \in \mc{U}$ and $a \bs{u} \in \mc{U}$ for all $a \in \b{R}$ and $\bs{u} \in \mc{U}$.
:::

## Finite Dimensional Vector Spaces {#sec-Finite_dimensional_vector_space}

A *list* of length $n$ is an ordered collection of $n$ elements. We denote lists without parenthesis as $\bs{v}_{1},...,\bs{v}_{n}$. By definition, a list has finite length.

A *linear combination* of a list of vectors $\bs{v}_{1},...,\bs{v}_{n} \in \mc{V}$  is a vector of the form $a_{1} \bs{v}_{1} + ... + a_{n} \bs{v}_{n}$ where $a_{1},...,a_{n} \in \b{R}$. 

The *span* of a list of vectors $\bs{v}_{1},...,\bs{v}_{n} \in \mc{V}$ is the set of all linear combinations of the form $a_{1} \bs{v}_{1} + ... + a_{n} \bs{v}_{n}$ where $a_{1},...,a_{n} \in \b{R}$ and is denoted by $\text{span}\pr{\bs{v}_{1},...,\bs{v}_{n}}$. If $\bs{v}_{1},...,\bs{v}_{n}$ spans $\mc{V}$, then $\text{span}\pr{\bs{v}_{1},...,\bs{v}_{n}} = \mc{V}$


::: {#def-Finite_dimensional_vector_space}
**[Finite dimensional vector space]{style="color: red;"}**

A vector space $\mc{V}$ is *finite dimensional* if some list of vectors $\bs{v}_{1},...,\bs{v}_{n} \in \mc{V}$ spans the space. 
:::

A list of vectors $\bs{v}_{1},...,\bs{v}_{n} \in \mc{V}$ is said to be *linearly independent* if its linear combination is $\bs{0}$ iff the scalars $a_{1},...,a_{n}$ are all $0$. On the contrary, a list is linearly dependent if a linear combination is $\bs{0}$ for some list of scalars $a_{1},...,a_{n}$ where not all are $0$. In a finite-dimensional vector space, the length of each linearly independent list of vectors is less than or equal to the length of every spanning list of vectors.

::: {#def-basis}
**[Basis]{style="color: red;"}**

A *basis* of $\mc{V}$ is a linearly independent list of vectors $\bs{v}_{1},...,\bs{v}_{n} \in \mc{V}$ that spans $\mc{V}$. An equivalent definition is that the list $\bs{v}_{1},...,\bs{v}_{n} \in \mc{V}$ is *basis* of $\mc{V}$ iff every $\bs{v} \in \mc{V}$ can be written as a unique linear combination of the list.
:::

Every finite dimensional vector space $\mc{V}$ has a basis. The *dimension* of $\mc{V}$ is given by the length of any of its basis. All bases of a finite dimensional vector space have the same length. A proper subspace always has a smaller dimension than the larger space. We will denote finite dimensional vector spaces with a superscript to indicate the dimension, for example, $\mc{V}^{n}$ or $P^{k}$.

## Real Inner Products and Norms {#sec-inner_prod_normed_spaces}

::: {#def-inner_prod}
**[Inner product]{style="color: red;"}** 

An *inner product* on $\mc{V}$ is an operation $\apr{\cdot, \cdot} : \mc{V} \times \mc{V} \rightarrow \b{R}$ such that for all $\bs{u}, \bs{v}, \bs{z} \in \mc{V}$ and for $a \in \b{R}$, we have

1. $\apr{\bs{u}, \bs v} = \apr{\bs v, \bs u}$
2. $\apr{\bs u, \bs v + a \bs z} = \apr{\bs u, \bs v} + a \apr{\bs u, \bs z}$
3. $\inpd{\bs u}{\bs u} \geq 0$
4. $\inpd{\bs u}{\bs u} = 0$ iff $\bs{u} = \bs{0}$
:::    

An real inner product space is a real vector space on which an inner product is defined. An inner product is not a requirement of a vector space.

::: {#def-norm}
**[Norm]{style="color: red;"}** 

A *norm* on $\mc{V}$ is an operation $\norm{\cdot} : \mc{V} \rightarrow \b{R}_{\geq 0}$ such that such that for all $\bs{u}, \bs{v} \in \mc{V}$ and for $a \in \b{R}$, we have

1. $\norm{a \bs u} = \abs{a} \norm{\bs u}$
2. $\norm{\bs u + \bs v} \leq \norm{\bs u} + \norm{\bs v}$
3. $\norm{\bs u} = 0$ iff $\bs u = \bs 0$
:::

A vector space equipped with a norm is called a normed vector space. To be more precise, we denote a norm of vector space $\mc{V}$ as $\norm{\cdot}_{\mc{V}}$ and similarly for norms of other vector spaces. Every inner product induces a norm. The induced norm is given by $\norm{\bs u} = \sqrt{\inpd{\bs u}{\bs u}}$.

## Euclidean Space {#sec-euclidean_space}

::: {#def-euclidean_vector_space}
An **[Euclidean vector space]{style="color: red;"}** $\b{E}$ is a finite dimensional real inner product space, whose inner product is the dot product. 
:::

We denote an $n$ dimensional Euclidean space by $\b{E}^{n}$. The Euclidean norm is induced by the dot product. 

::: {#def-affine_point_space}
An **[affine point space]{style="color: red;"}** $\mc{E}$ is a set of points on which the addition of two points is *not* defined, there is no unique zero element, and the difference between two points belongs to the Euclidean space associated with it.
:::

We denote an $n$ dimensional affine point space by $\mc{E}^{n}$. The term *point* is reserved for elements of $\mc{E}$ and the term *vector* for elements of $\b{E}$.

::: {#def-euclidean_space}
**[Euclidean space]{style="color: red;"}**

We denote the pair $\pr{\mc{E}^{n}, \b{E}^{n}}$ as an *Euclidean space*, to mean an affine point space such that the associated vector space is an Euclidean vector space. Choosing a point $o \in \mc{E}^{n}$ which we call the origin in $\mc{E}^{n}$, a point $x \in \mc{E}^{n}$ corresponds to a vector $\bs{x} \in \b{E}^{n}$ iff $o + \bs{x} = x$. We are particularly interested in the Euclidean space $\pr{\mc{E}^{3}, \b{E}^{3}}$. We formally define the vectors in $\b{E}^{n}$ to have units of length.
:::

## Components of Vectors {#sec-components_of_vectors}

To manipulate and work with vectors, we would like to assign them components. Let $\mc{F}= (1,\dots,n)$. Let a list of vectors $\pr{\bs{e}_{i}}_{i \in \mc{F}} \in \b{E}^{n}$ form a basis for $\b{E}^{n}$. Then for a vector $\bs{x} \in \b{E}^{n}$, we can write $\bs{x} = \sum_{i \in \mc{F}} x_{i} \bs{e}_{i}$. The *components* of $\bs{x}$ w.r.t. to the basis $\pr{\bs{e}_{i}}_{i \in \mc{F}}$ are the real numbers $(x_{i})_{i \in \mc{F}}$. We give the components a column matrix representation. For example, the components of a vector $\bs{x} \in \b{E}^{3}$ w.r.t a basis $\pr{\bs{e}_{1},\bs{e}_{2},\bs{e}_{3}}$ may be written as
$$
    \begin{bmatrix}
    a \\ b \\ c
    \end{bmatrix}
$$

where $a, b, c \in \b{R}$. The following is *not* a meaningful statement:
$$
\bs{x} =
    \begin{bmatrix}
    a \\ b \\ c
    \end{bmatrix}
$$

Instead, we write

$$
    \bs{x} = \sum_{i=1}^{3} x_{i} \bs{e}_{i}
$$